### ISSUE TITLE
necessity of upsampling f0 during data processing

### ISSUE THREAD

**Issue by cnlinxi** [zhangyongmao/VISinger2#9]
good work.

I see the following upsampling f0 operation in [dataset.py](https://github.com/zhangyongmao/VISinger2/blob/54a00d6d7da4de4f4037ab182e92b3b9102c2f11/egs/visinger2/dataset.py#L169):

```python

f0, _ = self.interpolate_f0(f0)
```

why do this? The naturalness of synthesized voice will decrease if I donot do this?

Thanks for your answer.

**Comment by zhangyongmao** [comment]
This is an operation to interpolate F0. Since the original F0 contains the classification of voiced segment (F0 > 0) and unvoiced segment (F0 == 0), direct prediction of the original F0 can result in the classification error of voiced segment and unvoiced segment. Interpolation of F0 can reduce the classification errors of voiced and unvoiced segments.

No interpolation is also possible, but the model may be more stable when interpolating F0.
